### PR TITLE
Adam Letizia's Skills Assessment

### PR DESCRIPTION
**Pull request by koalaty-code**

### CODE REVIEW

**Comment by jglozano** [comment]
Thanks for working on it! 

Looking at the code, there's one piece that's missing in Item 2 of the FizzLib section:
> Returns all the results from the evaluations as an enumerable structure

Currently your implementation wrapping the console and printing from within the FizzBuzz class. The requested approach is for the **FizzLib** library to return the results as an enumerable structure and the **FizzClient** prints out that list to the console.

**Comment by koalaty-code** [comment]
I have made the requested changes.

**Comment by jglozano** [comment]
thanks! I should have time this evening to review the code and run the app. Once I've done that, I will close the PR.

**Comment by jglozano** [comment]
Sorry for the delay with the review! Everything works as expected! Closing the PR

**Pull request closed without merging**
